export const RETRIEVE_USER_PROVIDER = 'FLEXICA_RETRIEVE_USER_PROVIDER';
export const AUTHENTICATOR_PROVIDER = 'FLEXICA_AUTHENTICATOR_PROVIDER';
export const PASSWORD_VALIDATOR_PROVIDER = 'FLEXICA_PASSWORD_VALIDATOR_PROVIDER';
